### ISSUE TITLE
Fixing Election A19 bug

### ISSUE THREAD

**Issue by Justin2997** [ageg/generateur-elections#1]
Salut @NewLunarFire. Je fais une liste ici des bug que on doit fixé pour la nouvelle version : 

- Faire un Docker file qui permet de fun le système en une seul commande
- Edit le README avec sa
- Avoir des erreurs plus user Friendly
- Permet d'édité la date (genre fichier de config)
- pouvoir donner les url google sheet peut-être pour ne pas devoir les télécharger
- Upload automatiquement les images des participants pour pas avoir le faire a main
- Affichier les config au user avant exécution
- Pouvoir configuré la date d'expiration

Si tu as en pas met ici, vais faire des PR pour d'aider :)

**Comment by NewLunarFire** [comment]
Je suis d'accord avec la plupart des points, mais:
- Pour Docker, tu peux faire un Dockerfile mais je ne veux pas forcer ça. C'est plus aisé pour moi de travailler avec un venv bien configuré. Donc on peut ajouter l'option Docker mais je ne le maintient pas.
- J'ai rajouté des erreurs quand il manque des colonnes dans le CSV. Il faudrait que j'en ajoute pour les problèmes de poste (il manquait VPAL)
- Je vais ajouter un fichier de config pour les trucs comme la date d'expiration et les informations de l'admin­. Pour les messages et les descriptions des questions je reprendre des templates Mako, mais mieux divisés. Je vais aussi afficher les config que le user passe avant de générer le formulaire.
- Je ne veux pas forcer l'utilisation de Google pour le générateur de formulaire. La gestion des photos  devrait être séparé du reste, dans son propre script, qui met les bons URL dans le CSV passé au générateur d'élections.

Je vais closer ton issue et en créer des plus petits pour travailler séparément dessus.
