### ISSUE TITLE
Créer Dockerfile

### ISSUE THREAD

**Issue by NewLunarFire** [ageg/generateur-elections#2]
@Justin2997 si tu veux travailler dessus.

Créer un Dockerfile qui simplifie la configuration de l'environnement.

**Comment by Justin2997** [comment]
I will ;)

**Comment by Justin2997** [comment]
Can you take a look at this : https://github.com/ageg/generateur-elections/pull/7 @NewLunarFire Thanks !

**Comment by NewLunarFire** [comment]
Parfait.
